### ISSUE TITLE
请问/api/self这个文件在哪里？

### ISSUE THREAD

**Issue by KAROTT7** [jiangqizheng/vue2-MiniQQ#11]
在action.js文件里的
    let self = {}
    let friends = {}
    await that.$http.get('/api/self')
/api/self 这个是怎么回事？初始化的数据我看不到。。。

**Comment by jiangqizheng** [comment]
初始化的数据在mockdata.json里。是通过webpack自带的服务器先读取数据然后然后接受请求后拿到的。
