### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by myronliu347** [jiangqizheng/vue2-MiniQQ#2]
* 程序打包下，放在github上吧，可以直接看到demo有助于涨star哦，
* MuseUI可以升级了哦。

最后赞一个，这个做的比较漂亮哦

**Comment by jiangqizheng** [comment]
恩，目前项目有部分内容还在写，所以暂时不打算打包，等到更加完善一些，并且目前正准备重构CSS样式，对一些地方进行兼容性的改善。

**Comment by jiangqizheng** [comment]
已经更新到muse-ui2.0.0了，写写赞赏，你的musue非常漂亮。
