### ISSUE TITLE
效果图的制作

### ISSUE THREAD

**Issue by zenga2** [jiangqizheng/vue2-MiniQQ#5]
楼主，那个效果图gif是怎么制作的，用的那个软件

**Comment by fhefh2015** [comment]
‘’‘
GIPHY Capture. The GIF Maker

https://itunes.apple.com/us/app/giphy-capture-the-gif-maker/id668208984?mt=12

可以试一试
’‘’

**Comment by zenga2** [comment]
好的，非常感谢
